// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type User struct {
	UserID           int32        `json:"user_id"`
	Firstname        string       `json:"firstname"`
	Lastname         string       `json:"lastname"`
	Email            string       `json:"email"`
	Password         string       `json:"password"`
	VerificationCode string       `json:"verification_code"`
	IsVerified       sql.NullBool `json:"is_verified"`
	CreatedAt        sql.NullTime `json:"created_at"`
	UpdatedAt        sql.NullTime `json:"updated_at"`
	DeletedAt        sql.NullTime `json:"deleted_at"`
}
