// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	RefreshTokenID int32        `json:"refresh_token_id"`
	UserID         int32        `json:"user_id"`
	Token          string       `json:"token"`
	Expiration     time.Time    `json:"expiration"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
}

type ResetToken struct {
	ID         int32     `json:"id"`
	UserID     int64     `json:"user_id"`
	Token      string    `json:"token"`
	ExpiryDate time.Time `json:"expiry_date"`
}
