// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// CreateRefreshToken: Creates a new refresh token
	// Purpose: Generate a refresh token for user authentication
	// Parameters:
	//   $1: user_id - ID of the user this token belongs to
	//   $2: token - The actual refresh token string
	//   $3: expiration - Expiration timestamp of the token
	// Returns: The created refresh token record (excluding sensitive fields if any)
	// Business Logic:
	//   - Sets both created_at and updated_at to current timestamp
	//   - Used in JWT refresh token rotation
	//   - Typically created during login/auth flows
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (*RefreshToken, error)
	CreateResetToken(ctx context.Context, arg CreateResetTokenParams) (*ResetToken, error)
	// DeleteRefreshToken: Permanently deletes a refresh token
	// Purpose: Invalidate a specific refresh token
	// Parameters:
	//   $1: token - The token string to delete
	// Business Logic:
	//   - Hard deletes the token record
	//   - Used during logout/token invalidation
	//   - Prevents token reuse after deletion
	DeleteRefreshToken(ctx context.Context, token string) error
	// DeleteRefreshTokenByUserId: Permanently deletes all tokens for a user
	// Purpose: Invalidate all refresh tokens for a user
	// Parameters:
	//   $1: user_id - ID of the user whose tokens to delete
	// Business Logic:
	//   - Hard deletes all tokens for the user
	//   - Used during password reset or account lock
	//   - Ensures complete session invalidation
	DeleteRefreshTokenByUserId(ctx context.Context, userID int32) error
	DeleteResetToken(ctx context.Context, userID int64) error
	// FindRefreshTokenByToken: Retrieves active refresh token by token string
	// Purpose: Validate and lookup refresh token
	// Parameters:
	//   $1: token - The refresh token string to find
	// Returns: The refresh token record if found and active
	// Business Logic:
	//   - Only returns non-deleted tokens
	//   - Used during token refresh operations
	//   - Helps prevent token reuse
	FindRefreshTokenByToken(ctx context.Context, token string) (*RefreshToken, error)
	// FindRefreshTokenByUserId: Retrieves latest active refresh token for user
	// Purpose: Get current valid refresh token for a user
	// Parameters:
	//   $1: user_id - ID of the user to find token for
	// Returns: The most recent refresh token for the user
	// Business Logic:
	//   - Returns only active (non-deleted) tokens
	//   - Orders by creation date (newest first)
	//   - Used for token management and validation
	//   - Limits to 1 result to get latest token
	FindRefreshTokenByUserId(ctx context.Context, userID int32) (*RefreshToken, error)
	GetResetToken(ctx context.Context, token string) (*ResetToken, error)
	// UpdateRefreshTokenByUserId: Updates refresh token for a user
	// Purpose: Rotate/refresh token for a user
	// Parameters:
	//   $1: user_id - ID of the user to update token for
	//   $2: token - New token string
	//   $3: expiration - New expiration timestamp
	// Business Logic:
	//   - Updates token and expiration fields
	//   - Sets updated_at to current time
	//   - Only modifies active tokens
	//   - Used during token rotation flows
	UpdateRefreshTokenByUserId(ctx context.Context, arg UpdateRefreshTokenByUserIdParams) (*RefreshToken, error)
}

var _ Querier = (*Queries)(nil)
