// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Product struct {
	ProductID int32        `json:"product_id"`
	Name      string       `json:"name"`
	Price     int64        `json:"price"`
	Stock     int32        `json:"stock"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}
