// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// AssignRoleToUser: Assigns a role to a user (creates a user-role relation)
	// Purpose: Role management for user access control
	// Parameters:
	//   $1: User ID
	//   $2: Role ID
	// Returns:
	//   user_role_id, user_id, role_id, timestamps (incl. deleted_at for future status check)
	// Business Logic:
	//   - Adds a new entry in the user_roles mapping table
	//   - Timestamps created_at and updated_at auto-set to current
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) (*UserRole, error)
	// CreateRole: Inserts a new role into the system
	// Purpose: Add new role definitions (e.g., Admin, Cashier, etc.)
	// Parameters:
	//   $1: Role name
	// Returns:
	//   Newly created role's full data (including timestamps)
	CreateRole(ctx context.Context, name string) (*Role, error)
	// DeleteAllPermanentRoles: Permanently deletes all soft-deleted roles
	// Purpose: Bulk cleanup of trashed roles
	// Parameters: None
	DeleteAllPermanentRoles(ctx context.Context) error
	// DeletePermanentRole: Permanently deletes a trashed role
	// Purpose: Remove role from DB after soft delete
	// Parameters:
	//   $1: Role ID
	DeletePermanentRole(ctx context.Context, roleID int32) error
	// GetActiveRoles: Retrieves only active (non-deleted) roles with optional search and pagination
	// Purpose: Display roles that are currently usable in the system
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, name, timestamps, and total_count
	GetActiveRoles(ctx context.Context, arg GetActiveRolesParams) ([]*GetActiveRolesRow, error)
	// GetRole: Retrieves role details by role_id
	// Purpose: Fetch a single role record (regardless of deleted status)
	// Parameters:
	//   $1: Role ID
	// Returns:
	//   role_id, name, and timestamps
	GetRole(ctx context.Context, roleID int32) (*Role, error)
	// GetRoleByName: Retrieves role by exact role name
	// Purpose: Check role existence or fetch role info based on name
	// Parameters:
	//   $1: Role name (exact match)
	// Returns:
	//   role_id, name, and timestamps
	GetRoleByName(ctx context.Context, name string) (*Role, error)
	// GetRoles: Retrieves all roles (active & trashed) with optional name search and pagination
	// Purpose: General listing of roles regardless of status
	// Parameters:
	//   $1: Search query (role name, nullable)
	//   $2: Limit (number of records per page)
	//   $3: Offset (starting index for pagination)
	// Returns:
	//   role_id, name, timestamps, and total_count (for pagination support)
	// Business Logic:
	//   - Supports fuzzy search on name
	//   - Includes both active and trashed roles
	//   - Useful for admin panels with filters and pagination
	GetRoles(ctx context.Context, arg GetRolesParams) ([]*GetRolesRow, error)
	// GetTrashedRoles: Retrieves only soft-deleted roles with optional search and pagination
	// Purpose: For trash/recycle bin management
	// Parameters:
	//   $1: Search query (nullable)
	//   $2: Limit
	//   $3: Offset
	// Returns:
	//   role_id, name, timestamps, and total_count
	GetTrashedRoles(ctx context.Context, arg GetTrashedRolesParams) ([]*GetTrashedRolesRow, error)
	// GetTrashedUserRoles: Retrieves all soft-deleted roles for a given user
	// Purpose: Review previously deleted role assignments for recovery or audit
	// Parameters:
	//   $1: User ID
	// Returns:
	//   user_role_id, user_id, role_id, name, timestamps
	// Business Logic:
	//   - Joins with roles to show role name
	//   - Orders by most recently trashed
	GetTrashedUserRoles(ctx context.Context, userID int32) ([]*GetTrashedUserRolesRow, error)
	// GetUserRoles: Retrieves all roles assigned to a specific user
	// Purpose: Identify the access level(s) of a user
	// Parameters:
	//   $1: User ID
	// Returns:
	//   List of roles (id, name, timestamps)
	GetUserRoles(ctx context.Context, userID int32) ([]*Role, error)
	// RemoveRoleFromUser: Permanently removes a role from a user
	// Purpose: Hard delete of a user-role mapping (bypasses trash)
	// Parameters:
	//   $1: User ID
	//   $2: Role ID
	// Business Logic:
	//   - Deletes the record instead of soft-deleting
	//   - Use cautiously if audit/history is important
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	// RestoreAllRoles: Restores all soft-deleted roles in bulk
	// Purpose: Bulk recovery of all trashed roles
	// Parameters: None
	RestoreAllRoles(ctx context.Context) error
	// RestoreRole: Restores a previously trashed role
	// Purpose: Undelete a soft-deleted role
	// Parameters:
	//   $1: Role ID
	RestoreRole(ctx context.Context, roleID int32) (*Role, error)
	// RestoreUserRole: Restores a trashed user-role relation
	// Purpose: Reactivate a previously soft-deleted user-role
	// Parameters:
	//   $1: user_role_id
	// Business Logic:
	//   - Clears the deleted_at field to mark as active again
	RestoreUserRole(ctx context.Context, userRoleID int32) error
	// TrashRole: Soft-deletes a role (moves to trash)
	// Purpose: Mark role as deleted without removing it permanently
	// Parameters:
	//   $1: Role ID
	TrashRole(ctx context.Context, roleID int32) (*Role, error)
	// TrashUserRole: Soft deletes a user-role mapping (moves to trash)
	// Purpose: Temporarily disable a role assignment without permanent deletion
	// Parameters:
	//   $1: user_role_id (primary key of the mapping)
	// Business Logic:
	//   - Sets deleted_at timestamp, indicating the relation is inactive
	TrashUserRole(ctx context.Context, userRoleID int32) error
	// UpdateRole: Updates role name by ID
	// Purpose: Modify role information (e.g., name correction)
	// Parameters:
	//   $1: Role ID
	//   $2: New role name
	// Returns:
	//   Updated role's data
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (*Role, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (*UserRole, error)
}

var _ Querier = (*Queries)(nil)
