// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// CalculateTotalPrice: Calculates total price of active order items for a specific order
	// Purpose: Provides the aggregated monetary value of an order
	// Parameters:
	//   $1: order_id - identifier of the order
	// Returns:
	//   total_price: Sum of (quantity * price) for all active items in the order
	// Business Logic:
	//   - Ignores soft-deleted items
	//   - Ensures result is zero if no items exist
	CalculateTotalPrice(ctx context.Context, orderID int32) (int32, error)
	// CreateOrder: Creates a new order record
	// Purpose: Register a new transaction in the system
	// Parameters:
	//   $2: user_id - ID of the user processing the order
	//   $3: total_price - Numeric total amount of the order
	// Returns: The complete created order record
	// Business Logic:
	//   - Automatically sets created_at timestamp
	//   - Requires merchant_id, user_id and total_price
	//   - Typically followed by order item creation
	CreateOrder(ctx context.Context, arg CreateOrderParams) (*Order, error)
	// CreateOrderItem: Inserts a new order item record
	// Purpose: Adds a product to a specific order
	// Parameters:
	//   $1: order_id
	//   $2: product_id
	//   $3: quantity
	//   $4: price
	// Returns:
	//   The newly created order item
	// Business Logic:
	//   - Assumes quantity and price are validated in application layer
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (*OrderItem, error)
	// DeleteAllPermanentOrders: Purges all cancelled orders
	// Purpose: Clean up all soft-deleted order records
	// Business Logic:
	//   - Irreversible bulk deletion operation
	//   - Only affects already cancelled orders
	//   - Typically used during database maintenance
	//   - Should be restricted to admin users
	DeleteAllPermanentOrders(ctx context.Context) error
	// DeleteAllPermanentOrdersItem: Permanently deletes all trashed order items
	// Purpose: Performs hard delete of all soft-deleted items
	// Parameters: None
	// Returns: None
	// Business Logic:
	//   - Used for data cleanup or archival enforcement
	DeleteAllPermanentOrdersItem(ctx context.Context) error
	// DeleteOrderItemPermanently: Permanently deletes a trashed order item
	// Purpose: Removes the record entirely from the database
	// Parameters:
	//   $1: order_item_id
	// Returns: None
	// Business Logic:
	//   - Only deletes if already soft-deleted
	//   - Irreversible action
	DeleteOrderItemPermanently(ctx context.Context, orderID int32) error
	// DeleteOrderPermanently: Hard-deletes an order
	// Purpose: Completely remove order from database
	// Parameters:
	//   $1: order_id - UUID of order to delete
	// Business Logic:
	//   - Permanent deletion of already cancelled orders
	//   - No return value (exec-only operation)
	//   - Irreversible action - use with caution
	//   - Should trigger deletion of related order_items
	DeleteOrderPermanently(ctx context.Context, orderID int32) error
	// GetOrderByID: Retrieves an active order by ID
	// Purpose: Fetch order details for display/processing
	// Parameters:
	//   $1: order_id - UUID of the order to retrieve
	// Returns: Full order record if found and active
	// Business Logic:
	//   - Excludes soft-deleted orders
	//   - Used for order viewing, receipts, and processing
	//   - Typically joined with order_items in application
	GetOrderByID(ctx context.Context, orderID int32) (*Order, error)
	// GetOrderItems: Retrieves active order items with pagination and search
	// Purpose: Provides paginated listing of non-deleted order items for display or reporting
	// Parameters:
	//   $1: Search keyword (matches order_id or product_id, optional)
	//   $2: Limit (number of records per page)
	//   $3: Offset (starting record index)
	// Returns:
	//   All matching order item fields
	//   total_count: Total number of results ignoring pagination (for frontend pagination UI)
	// Business Logic:
	//   - Filters out soft-deleted items
	//   - Supports keyword-based filtering
	//   - Includes total result count via window function
	GetOrderItems(ctx context.Context, arg GetOrderItemsParams) ([]*GetOrderItemsRow, error)
	// GetOrderItemsActive: Retrieves active order items (duplicate-safe with GetOrderItems)
	// Purpose: Lists active (non-deleted) order items with pagination and optional search
	// Parameters:
	//   $1: Search keyword (order_id or product_id, optional)
	//   $2: Limit (pagination size)
	//   $3: Offset (pagination start)
	// Returns:
	//   Order item fields plus total matching count
	// Business Logic:
	//   - Behaves similarly to GetOrderItems
	//   - Used when clarity between active/trashed context is required
	GetOrderItemsActive(ctx context.Context, arg GetOrderItemsActiveParams) ([]*GetOrderItemsActiveRow, error)
	// GetOrderItemsByOrder: Retrieves active order items for a specific order
	// Purpose: Fetches all non-deleted order items under one order
	// Parameters:
	//   $1: order_id
	// Returns:
	//   List of active order items
	// Business Logic:
	//   - Excludes soft-deleted entries
	GetOrderItemsByOrder(ctx context.Context, orderID int32) ([]*OrderItem, error)
	// GetOrderItemsTrashed: Retrieves soft-deleted order items with pagination
	// Purpose: Allows review and management of trashed order items
	// Parameters:
	//   $1: Search keyword (order_id or product_id, optional)
	//   $2: Limit (number of rows per page)
	//   $3: Offset (starting point for pagination)
	// Returns:
	//   All matching deleted order item fields
	//   total_count: Total number of trashed results
	// Business Logic:
	//   - Only includes records with non-null deleted_at (trashed)
	//   - Enables optional keyword search and pagination
	//   - Sorted by deletion date for recent trash activity review
	GetOrderItemsTrashed(ctx context.Context, arg GetOrderItemsTrashedParams) ([]*GetOrderItemsTrashedRow, error)
	// GetOrders: Retrieves paginated list of active orders with search capability
	// Purpose: List all active orders for management UI
	// Parameters:
	//   $1: search_term - Optional text to filter orders by ID or total price (NULL for no filter)
	//   $2: limit - Maximum number of records to return (pagination limit)
	//   $3: offset - Number of records to skip (pagination offset)
	// Returns:
	//   All order fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted orders (deleted_at IS NULL)
	//   - Supports partial text matching on order_id and total_price fields (case-insensitive)
	//   - Returns newest orders first (created_at DESC)
	//   - Provides total_count for client-side pagination
	//   - Uses window function COUNT(*) OVER() for efficient total count
	GetOrders(ctx context.Context, arg GetOrdersParams) ([]*GetOrdersRow, error)
	// GetOrdersActive: Retrieves paginated list of active orders (identical to GetOrders)
	// Purpose: Maintains consistent API pattern with other active/trashed endpoints
	// Parameters:
	//   $1: search_term - Optional filter text for order ID or price
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns:
	//   Active order records with total_count
	// Business Logic:
	//   - Same functionality as GetOrders
	//   - Exists for consistency in API design patterns
	// Note: Could be consolidated with GetOrders if duplicate functionality is undesired
	GetOrdersActive(ctx context.Context, arg GetOrdersActiveParams) ([]*GetOrdersActiveRow, error)
	// GetOrdersTrashed: Retrieves paginated list of soft-deleted orders
	// Purpose: View and manage deleted orders for potential restoration
	// Parameters:
	//   $1: search_term - Optional text to filter trashed orders
	//   $2: limit - Maximum records per page
	//   $3: offset - Records to skip
	// Returns:
	//   Trashed order records with total_count
	// Business Logic:
	//   - Only returns soft-deleted records (deleted_at IS NOT NULL)
	//   - Maintains same search functionality as active order queries
	//   - Preserves chronological sorting (newest first)
	//   - Used in order recovery/audit interfaces
	//   - Includes total_count for pagination in trash management UI
	GetOrdersTrashed(ctx context.Context, arg GetOrdersTrashedParams) ([]*GetOrdersTrashedRow, error)
	// RestoreAllOrders: Mass restoration of cancelled orders
	// Purpose: Recover all trashed orders at once
	// Business Logic:
	//   - Reactivates all soft-deleted orders
	//   - No parameters needed (bulk operation)
	//   - Typically used during system recovery
	RestoreAllOrders(ctx context.Context) error
	// RestoreAllOrdersItem: Restores all soft-deleted order items
	// Purpose: Mass recovery of trashed items
	// Parameters: None
	// Returns: None
	// Business Logic:
	//   - Resets deleted_at to NULL for all trashed items
	RestoreAllOrdersItem(ctx context.Context) error
	// RestoreOrder: Recovers a soft-deleted order
	// Purpose: Reactivate a cancelled order
	// Parameters:
	//   $1: order_id - UUID of order to restore
	// Returns: The restored order record
	// Business Logic:
	//   - Nullifies deleted_at field
	//   - Only works on previously cancelled orders
	//   - Maintains all original order data
	RestoreOrder(ctx context.Context, orderID int32) (*Order, error)
	// RestoreOrderItem: Restores a previously trashed order item
	// Purpose: Undoes a soft-delete action
	// Parameters:
	//   $1: order_item_id
	// Returns:
	//   The restored order item
	// Business Logic:
	//   - Only restores items currently soft-deleted
	RestoreOrderItem(ctx context.Context, orderID int32) (*OrderItem, error)
	// TrashOrderItem: Soft-deletes a specific order item
	// Purpose: Marks an item as deleted without removing it from DB
	// Parameters:
	//   $1: order_item_id
	// Returns:
	//   The soft-deleted order item
	// Business Logic:
	//   - Preserves record for potential restoration or audit
	TrashOrderItem(ctx context.Context, orderID int32) (*OrderItem, error)
	// TrashedOrder: Soft-deletes an order
	// Purpose: Cancel/void an order without permanent deletion
	// Parameters:
	//   $1: order_id - UUID of order to cancel
	// Returns: The soft-deleted order record
	// Business Logic:
	//   - Sets deleted_at to current timestamp
	//   - Preserves order data for reporting
	//   - Only processes active orders
	//   - Can be restored via RestoreOrder
	TrashedOrder(ctx context.Context, orderID int32) (*Order, error)
	// UpdateOrder: Modifies order information
	// Purpose: Update order details (primarily total price)
	// Parameters:
	//   $1: order_id - UUID of order to update
	//   $2: total_price - New total amount
	// Returns: Updated order record
	// Business Logic:
	//   - Auto-updates updated_at timestamp
	//   - Only modifies active (non-deleted) orders
	//   - Used when order items change
	//   - Should trigger recalculation of total_price
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (*Order, error)
	// UpdateOrderItem: Updates quantity and price of an existing order item
	// Purpose: Allows modification of product details in an order
	// Parameters:
	//   $1: order_item_id
	//   $2: new quantity
	//   $3: new price
	// Returns:
	//   The updated order item
	// Business Logic:
	//   - Applies changes only to active items
	//   - Automatically updates `updated_at` timestamp
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (*OrderItem, error)
}

var _ Querier = (*Queries)(nil)
