// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	OrderID    int32            `json:"order_id"`
	UserID     int32            `json:"user_id"`
	TotalPrice int32            `json:"total_price"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type OrderItem struct {
	OrderItemID int32            `json:"order_item_id"`
	OrderID     int32            `json:"order_id"`
	ProductID   int32            `json:"product_id"`
	Quantity    int32            `json:"quantity"`
	Price       int32            `json:"price"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}
