// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID           int32            `json:"user_id"`
	Firstname        string           `json:"firstname"`
	Lastname         string           `json:"lastname"`
	Email            string           `json:"email"`
	Password         string           `json:"password"`
	VerificationCode string           `json:"verification_code"`
	IsVerified       *bool            `json:"is_verified"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
}
