// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO
    products (name, price, stock)
VALUES ($1, $2, $3)
RETURNING
    product_id, name, price, stock, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	Name  string `json:"name"`
	Price int64  `json:"price"`
	Stock int32  `json:"stock"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (*Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.Price, arg.Stock)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const deleteAllPermanentProducts = `-- name: DeleteAllPermanentProducts :exec
DELETE FROM products WHERE deleted_at IS NOT NULL
`

func (q *Queries) DeleteAllPermanentProducts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllPermanentProducts)
	return err
}

const deleteProductPermanently = `-- name: DeleteProductPermanently :exec
DELETE FROM products
WHERE
    product_id = $1
    AND deleted_at IS NOT NULL
`

func (q *Queries) DeleteProductPermanently(ctx context.Context, productID int32) error {
	_, err := q.db.Exec(ctx, deleteProductPermanently, productID)
	return err
}

const getActiveProducts = `-- name: GetActiveProducts :many
SELECT product_id, name, price, stock, created_at, updated_at, deleted_at, COUNT(*) OVER () AS total_count
FROM products AS p
WHERE
    p.deleted_at IS NULL
    AND (
        $1::TEXT IS NULL
        OR p.name ILIKE '%' || $1 || '%'
    )
ORDER BY p.created_at DESC
LIMIT $2
OFFSET
    $3
`

type GetActiveProductsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetActiveProductsRow struct {
	ProductID  int32            `json:"product_id"`
	Name       string           `json:"name"`
	Price      int64            `json:"price"`
	Stock      int32            `json:"stock"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
	TotalCount int64            `json:"total_count"`
}

func (q *Queries) GetActiveProducts(ctx context.Context, arg GetActiveProductsParams) ([]*GetActiveProductsRow, error) {
	rows, err := q.db.Query(ctx, getActiveProducts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetActiveProductsRow
	for rows.Next() {
		var i GetActiveProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT product_id, name, price, stock, created_at, updated_at, deleted_at
FROM products AS p
WHERE
    p.product_id = $1
    AND p.deleted_at IS NULL
`

func (q *Queries) GetProductByID(ctx context.Context, productID int32) (*Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, productID)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getProductByIdTrashed = `-- name: GetProductByIdTrashed :one
SELECT product_id, name, price, stock, created_at, updated_at, deleted_at FROM products AS p WHERE p.product_id = $1
`

func (q *Queries) GetProductByIdTrashed(ctx context.Context, productID int32) (*Product, error) {
	row := q.db.QueryRow(ctx, getProductByIdTrashed, productID)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getProducts = `-- name: GetProducts :many
SELECT product_id, name, price, stock, created_at, updated_at, deleted_at, COUNT(*) OVER () AS total_count
FROM products AS p
WHERE
    p.deleted_at IS NULL
    AND (
        $1::TEXT IS NULL
        OR p.name ILIKE '%' || $1 || '%'
    )
ORDER BY p.created_at DESC
LIMIT $2
OFFSET
    $3
`

type GetProductsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetProductsRow struct {
	ProductID  int32            `json:"product_id"`
	Name       string           `json:"name"`
	Price      int64            `json:"price"`
	Stock      int32            `json:"stock"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
	TotalCount int64            `json:"total_count"`
}

func (q *Queries) GetProducts(ctx context.Context, arg GetProductsParams) ([]*GetProductsRow, error) {
	rows, err := q.db.Query(ctx, getProducts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetProductsRow
	for rows.Next() {
		var i GetProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrashedProducts = `-- name: GetTrashedProducts :many
SELECT product_id, name, price, stock, created_at, updated_at, deleted_at, COUNT(*) OVER () AS total_count
FROM products AS p
WHERE
    p.deleted_at IS NOT NULL
    AND (
        $1::TEXT IS NULL
        OR p.name ILIKE '%' || $1 || '%'
    )
ORDER BY p.created_at DESC
LIMIT $2
OFFSET
    $3
`

type GetTrashedProductsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetTrashedProductsRow struct {
	ProductID  int32            `json:"product_id"`
	Name       string           `json:"name"`
	Price      int64            `json:"price"`
	Stock      int32            `json:"stock"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
	TotalCount int64            `json:"total_count"`
}

func (q *Queries) GetTrashedProducts(ctx context.Context, arg GetTrashedProductsParams) ([]*GetTrashedProductsRow, error) {
	rows, err := q.db.Query(ctx, getTrashedProducts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetTrashedProductsRow
	for rows.Next() {
		var i GetTrashedProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreAllProducts = `-- name: RestoreAllProducts :exec
UPDATE products
SET
    deleted_at = NULL
WHERE
    deleted_at IS NOT NULL
`

func (q *Queries) RestoreAllProducts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreAllProducts)
	return err
}

const restoreProduct = `-- name: RestoreProduct :one
UPDATE products
SET
    deleted_at = NULL
WHERE
    product_id = $1
    AND deleted_at IS NOT NULL
RETURNING
    product_id, name, price, stock, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreProduct(ctx context.Context, productID int32) (*Product, error) {
	row := q.db.QueryRow(ctx, restoreProduct, productID)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const trashProduct = `-- name: TrashProduct :one
UPDATE products
SET
    deleted_at = current_timestamp
WHERE
    product_id = $1
    AND deleted_at IS NULL
RETURNING
    product_id, name, price, stock, created_at, updated_at, deleted_at
`

func (q *Queries) TrashProduct(ctx context.Context, productID int32) (*Product, error) {
	row := q.db.QueryRow(ctx, trashProduct, productID)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    name = $2,
    price = $3,
    stock = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE
    product_id = $1
    AND deleted_at IS NULL
RETURNING
    product_id, name, price, stock, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	ProductID int32  `json:"product_id"`
	Name      string `json:"name"`
	Price     int64  `json:"price"`
	Stock     int32  `json:"stock"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (*Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ProductID,
		arg.Name,
		arg.Price,
		arg.Stock,
	)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateProductCountStock = `-- name: UpdateProductCountStock :one
UPDATE products
SET
    stock = $2
WHERE
    product_id = $1
    AND deleted_at IS NULL
RETURNING
    product_id, name, price, stock, created_at, updated_at, deleted_at
`

type UpdateProductCountStockParams struct {
	ProductID int32 `json:"product_id"`
	Stock     int32 `json:"stock"`
}

func (q *Queries) UpdateProductCountStock(ctx context.Context, arg UpdateProductCountStockParams) (*Product, error) {
	row := q.db.QueryRow(ctx, updateProductCountStock, arg.ProductID, arg.Stock)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}
