// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (*Product, error)
	DeleteAllPermanentProducts(ctx context.Context) error
	DeleteProductPermanently(ctx context.Context, productID int32) error
	GetActiveProducts(ctx context.Context, arg GetActiveProductsParams) ([]*GetActiveProductsRow, error)
	GetProductByID(ctx context.Context, productID int32) (*Product, error)
	GetProductByIdTrashed(ctx context.Context, productID int32) (*Product, error)
	GetProducts(ctx context.Context, arg GetProductsParams) ([]*GetProductsRow, error)
	GetTrashedProducts(ctx context.Context, arg GetTrashedProductsParams) ([]*GetTrashedProductsRow, error)
	RestoreAllProducts(ctx context.Context) error
	RestoreProduct(ctx context.Context, productID int32) (*Product, error)
	TrashProduct(ctx context.Context, productID int32) (*Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (*Product, error)
	UpdateProductCountStock(ctx context.Context, arg UpdateProductCountStockParams) (*Product, error)
}

var _ Querier = (*Queries)(nil)
